"""Async PostGIS access for the API.

An ``AsyncConnectionPool`` is opened at start-up and closed at shutdown. Every
query is written out in SQL rather than generated by an ORM: the spatial
queries here are hand-tuned, and keeping them literal makes it possible to read
a response and know exactly which rows produced it.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator, Sequence

from backend.config import settings

logger = logging.getLogger(__name__)

_pool: Any = None


class DatabaseUnavailable(RuntimeError):
    """PostGIS is unreachable. Handlers convert this into a status badge."""


async def open_pool() -> None:
    """Create the connection pool. Called from the FastAPI lifespan hook."""
    global _pool
    if _pool is not None:
        return
    from psycopg_pool import AsyncConnectionPool

    _pool = AsyncConnectionPool(
        conninfo=settings.database_url,
        min_size=settings.db_pool_min,
        max_size=settings.db_pool_max,
        open=False,
        # A request should fail fast with a badge rather than hang on a dead DB.
        timeout=10.0,
    )
    await _pool.open(wait=True, timeout=15.0)
    logger.info("PostGIS pool opened (%d-%d)", settings.db_pool_min, settings.db_pool_max)


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None
        logger.info("PostGIS pool closed")


@asynccontextmanager
async def cursor() -> AsyncIterator[Any]:
    """Yield an async cursor, translating driver failures to our own type."""
    if _pool is None:
        raise DatabaseUnavailable("Connection pool is not open")
    try:
        async with _pool.connection() as conn:
            async with conn.cursor() as cur:
                yield cur
    except DatabaseUnavailable:
        raise
    except Exception as exc:  # noqa: BLE001 - psycopg raises many concrete types
        raise DatabaseUnavailable(f"PostGIS query failed: {exc}") from exc


async def fetch_all(sql: str, params: Sequence[Any] | None = None) -> list[tuple]:
    async with cursor() as cur:
        await cur.execute(sql, params or ())
        return await cur.fetchall()


async def fetch_one(sql: str, params: Sequence[Any] | None = None) -> tuple | None:
    async with cursor() as cur:
        await cur.execute(sql, params or ())
        return await cur.fetchone()


async def execute(sql: str, params: Sequence[Any] | None = None) -> int:
    async with cursor() as cur:
        await cur.execute(sql, params or ())
        return cur.rowcount


async def health_check() -> dict:
    """Structured health for the telemetry endpoint; reports rather than raises."""
    try:
        row = await fetch_one("SELECT 1, postgis_version()")
        return {
            "service": "postgis",
            "healthy": bool(row and row[0] == 1),
            "detail": f"PostGIS {row[1]}" if row else "no response",
        }
    except DatabaseUnavailable as exc:
        return {"service": "postgis", "healthy": False, "detail": str(exc)}


async def apply_schema() -> None:
    """Apply the idempotent schema file at start-up."""
    from pathlib import Path

    schema_path = Path(__file__).resolve().parent / "sql" / "001_schema.sql"
    if not schema_path.exists():  # pragma: no cover - packaging guard
        logger.warning("Schema file not found at %s; skipping", schema_path)
        return
    async with cursor() as cur:
        await cur.execute(schema_path.read_text(encoding="utf-8"))
    logger.info("Schema applied from %s", schema_path)
